"""empty message

Revision ID: 053da46248c0
Revises: ec9b648a18c8
Create Date: 2021-04-11 12:41:06.795052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "053da46248c0"
down_revision = "ec9b648a18c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("verification_codes")
    # ### end Alembic commands ###
